src/main/java/com/jaamsim/web/model/Configuration.java
package com.jaamsim.web.model;

import javax.persistence.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Date;
import java.util.List;

/**
 * Created by tristano on 12/12/15.
 */
@Entity
@Table(name = "jaamsim_configuration")
public class Configuration {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    private String name;

    @Lob
    private byte[] file;

    private Date uploadedTime;

    @OneToOne
    private User user;

    @OneToMany
    private List<Group> groups;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public String getUrlEncodedName() {
        try {
            return URLEncoder.encode(name, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            return name;
        }
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getSize() {
        return file != null ? file.length / 1024 : 0;
    }

    public byte[] getFile() {
        return file;
    }

    public void setFile(byte[] file) {
        this.file = file;
    }

    public Date getUploadedTime() {
        return uploadedTime;
    }

    public void setUploadedTime(Date uploadedTime) {
        this.uploadedTime = uploadedTime;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Group> getGroups() {
        return groups;
    }

    public void setGroups(List<Group> group) {
        this.groups = group;
    }
}

src/main/java/com/jaamsim/web/model/Group.java
package com.jaamsim.web.model;

import javax.persistence.*;
import java.util.List;

/**
 * Created by tristano on 12/12/15.
 */
@Entity
@Table(name = "jaamsim_group")
public class Group {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @OneToMany
    private List<User> users;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
}

src/main/java/com/jaamsim/web/model/Role.java
package com.jaamsim.web.model;

/**
 * Created by tristano on 12/12/15.
 */
public enum Role {
    ADMIN, USER
}

src/main/java/com/jaamsim/web/model/User.java
package com.jaamsim.web.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by tristano on 12/12/15.
 */
@Entity
@Table(name = "jaamsim_user")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int userId;

    @NotNull
    private String email;

    @NotNull
    private String password;

    @Column(columnDefinition="tinyint(1) default 1")
    private boolean enabled;

    @Enumerated(EnumType.STRING)
    @Column(name = "jaamsim_role")
    private Role role;

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}

src/main/java/com/jaamsim/web/model/simulation/State.java
package com.jaamsim.web.model.simulation;

/**
 * Created by tristano on 12/12/15.
 */
public enum State {
    NEW,
    CONFIGURED,
    RUNNING,
    PAUSED,
    FINISHED,
    FAILED,
    ABORTED
}

src/main/java/com/jaamsim/web/controller/ConfigurationController.java
package com.jaamsim.web.controller;

import com.jaamsim.web.dao.ConfigurationDao;
import com.jaamsim.web.dao.ReportDao;
import com.jaamsim.web.dao.SimulationDao;
import com.jaamsim.web.model.Configuration;
import com.jaamsim.web.model.simulation.Report;
import com.jaamsim.web.model.User;
import com.jaamsim.web.model.simulation.Simulation;
import com.jaamsim.web.model.simulation.State;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpSession;
import java.util.List;

import static com.jaamsim.web.constants.WebConstants.WEB_CONFIGURATION;
import static com.jaamsim.web.constants.WebConstants.WEB_JSP;

/**
 * Created by tristano on 06/01/16.
 */
@Controller
@RequestMapping("/sim")
public class ConfigurationController {

    private final static String CONFIGURATION_FILE = "configurationFile";

    @Autowired
    private ConfigurationDao configurationDao;

    @Autowired
    private SimulationDao simulationDao;

    @Autowired
    private ReportDao reportDao;

    @RequestMapping(path = "/configuration/{id}", method = RequestMethod.GET)
    public String getConfigurations(@PathVariable("id") int configurationId, HttpSession session, Model model) {

        User user = (User) session.getAttribute("user");

        Configuration configuration = configurationDao.findByIdAndUser(configurationId, user);
        Simulation simulation = simulationDao.findByUserAndConfigurationAndState(user, configuration, State.RUNNING);
        List<Simulation> simulations = simulationDao.findByUserAndConfigurationOrderByStartDesc(user, configuration);
        List<Report> reports = reportDao.getAllByConfiguration(configuration);

        model.addAttribute("currentSimulation", simulation);
        model.addAttribute("configuration", configuration);
        model.addAttribute("simulations", simulations);
        model.addAttribute("reports", reports);

        return WEB_JSP + WEB_CONFIGURATION;
    }

}

src/main/java/com/jaamsim/web/controller/ConfigurationsController.java
package com.jaamsim.web.controller;

import com.jaamsim.web.dao.ConfigurationDao;
import com.jaamsim.web.model.Configuration;
import com.jaamsim.web.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import javax.servlet.http.HttpSession;
import java.util.Calendar;
import java.util.List;

import static com.jaamsim.web.constants.WebConstants.*;

/**
 * Created by tristano on 06/01/16.
 */
@Controller
@RequestMapping("/sim")
public class ConfigurationsController {

    private final static String CONFIGURATION_FILE = "configurationFile";

    @Autowired
    private ConfigurationDao configurationDao;

    @RequestMapping(path = "/configurations", method = RequestMethod.GET)
    public String getConfigurations(HttpSession session, Model model) {

        User user = (User) session.getAttribute("user");

        List<Configuration> configurations = configurationDao.findAllByUser(user);

        model.addAttribute("configurations", configurations);

        return WEB_JSP + WEB_CONFIGURATIONS;
    }

    @RequestMapping(path = "/configurations/upload", method = RequestMethod.POST)
    public @ResponseBody String uploadConfiguration(MultipartHttpServletRequest request, HttpSession session) {

        MultipartFile file = request.getFileMap().get(CONFIGURATION_FILE);

        User user = (User) session.getAttribute("user");
        String fileName = file.getOriginalFilename();

        Configuration configuration = configurationDao.findByUserAndName(user, fileName);

        if (!file.isEmpty()) {
            try {

                byte[] bytes = file.getBytes();

                if(configuration == null) {
                    configuration = new Configuration();
                    configuration.setUser(user);
                }

                configuration.setName(fileName);
                configuration.setFile(bytes);
                configuration.setUploadedTime(Calendar.getInstance().getTime());

                configurationDao.save(configuration);

                return "File uploaded!";
            } catch (Exception e) {
                return "Uploading file [" + fileName + "] failed: " + e.getMessage();
            }
        } else {
            return "File [" + fileName + "] empty!";
        }
    }
}

src/main/java/com/jaamsim/web/controller/ExecutionController.java
package com.jaamsim.web.controller;

import com.jaamsim.web.dao.ConfigurationDao;
import com.jaamsim.web.dao.SimulationDao;
import com.jaamsim.web.model.Configuration;
import com.jaamsim.web.model.User;
import com.jaamsim.web.model.simulation.Simulation;
import com.jaamsim.web.model.simulation.State;
import com.jaamsim.web.process.ProcessSimulation;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpSession;
import java.util.Calendar;

import static com.jaamsim.web.constants.WebConstants.WEB_CONFIGURATION;
import static com.jaamsim.web.constants.WebConstants.WEB_SIM;
import static com.jaamsim.web.constants.WebConstants.WEB_REDIRECT;

/**
 * Created by tristano on 06/01/16.
 */
@Controller
@RequestMapping("/sim")
public class ExecutionController {
    private static final Logger LOG = LogManager.getLogger(ExecutionController.class);

    @Autowired
    ServletContext context;

    @Autowired
    private ConfigurationDao configurationDao;

    @Autowired
    private SimulationDao simulationDao;

    @Autowired
    private ProcessSimulation processSimulation;

    @RequestMapping(path = "/execute/{id}", method = RequestMethod.POST)
    public String execute(@PathVariable("id") int configurationId, HttpSession session) {

        User user = (User) session.getAttribute("user");

        Configuration configuration = configurationDao.findByIdAndUser(configurationId, user);

        Simulation simulation = simulationDao.findByUserAndConfigurationAndState(user, configuration, State.RUNNING);

        if(simulation == null) {
            LOG.info("Starting a new session with configuration file " + configuration.getName());

            simulation = new Simulation();
            simulation.setUser(user);
            simulation.setStart(Calendar.getInstance().getTime());
            simulation.setConfiguration(configuration);
            simulation.setState(State.NEW);
            simulationDao.save(simulation);

            processSimulation.execute(simulation);

            // TODO register listener for updating state and for registering completion
            simulation.setState(State.RUNNING);
            simulationDao.save(simulation);
        }

        return WEB_REDIRECT + WEB_SIM + WEB_CONFIGURATION + "/" + configurationId;
    }

    @RequestMapping(path = "/executing/{id}", method = RequestMethod.GET, produces = "application/json")
    public @ResponseBody
    ExecutingData executing(@PathVariable("id") int configurationId, HttpSession session) {

        User user = (User) session.getAttribute("user");

        Configuration configuration = configurationDao.findByIdAndUser(configurationId, user);

        Simulation simulation = simulationDao.findByUserAndConfigurationAndState(user, configuration, State.RUNNING);

        if(simulation != null) {
            return new ExecutingData(simulation.getProgress(), simulation.getState().equals(State.RUNNING));
        } else {
            return new ExecutingData(0, false);
        }
    }

    private static class ExecutingData {
        private int progress;
        private boolean executing;

        public ExecutingData(int progress, boolean executing) {
            this.progress = progress;
            this.executing = executing;
        }

        public int getProgress() {
            return progress;
        }

        public void setProgress(int progress) {
            this.progress = progress;
        }

        public boolean isExecuting() {
            return executing;
        }

        public void setExecuting(boolean executing) {
            this.executing = executing;
        }
    }
}

src/main/java/com/jaamsim/web/controller/LoginController.java
package com.jaamsim.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpSession;

import static com.jaamsim.web.constants.WebConstants.WEB_REDIRECT;
import static com.jaamsim.web.constants.WebConstants.WEB_SIM;
import static com.jaamsim.web.constants.WebConstants.WEB_MAIN;

/**
 * Created by tristano on 06/01/16.
 */
@Controller
@RequestMapping("/sim")
public class LoginController {

    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String login(HttpSession session) {

        return WEB_REDIRECT + WEB_SIM + WEB_MAIN;
    }
}

src/main/java/com/jaamsim/web/controller/MainController.java
package com.jaamsim.web.controller;

import com.jaamsim.web.dao.ConfigurationDao;
import com.jaamsim.web.dao.SimulationDao;
import com.jaamsim.web.model.Configuration;
import com.jaamsim.web.model.User;
import com.jaamsim.web.model.simulation.Simulation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import javax.servlet.http.HttpSession;
import java.util.Calendar;
import java.util.List;

import static com.jaamsim.web.constants.WebConstants.WEB_CONFIGURATIONS;
import static com.jaamsim.web.constants.WebConstants.WEB_JSP;
import static com.jaamsim.web.constants.WebConstants.WEB_MAIN;

/**
 * Created by tristano on 10/01/16.
 */
@Controller
@RequestMapping("/sim")
public class MainController {

    @Autowired
    private SimulationDao simulationDao;

    @RequestMapping(path = "/main", method = RequestMethod.GET)
    public String getConfigurations(HttpSession session, Model model) {

        User user = (User) session.getAttribute("user");

        List<Simulation> simulations = simulationDao.findAllByUserOrderByStartDesc(user);

        model.addAttribute("simulations", simulations);

        return WEB_JSP + WEB_MAIN;
    }
}

src/main/java/com/jaamsim/web/controller/ReportController.java
package com.jaamsim.web.controller;

import com.jaamsim.web.dao.ReportDao;
import com.jaamsim.web.model.User;
import com.jaamsim.web.model.simulation.Report;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Created by tristano on 06/01/16.
 */
@Controller
@RequestMapping("/sim/configuration")
public class ReportController {

    @Autowired
    private ReportDao reportDao;

    @RequestMapping(path = "/report/{id}", method = RequestMethod.GET, produces= MediaType.APPLICATION_OCTET_STREAM_VALUE)
    public @ResponseBody byte[] getReport(@PathVariable("id") int reportId, HttpSession session, HttpServletResponse response) {

        User user = (User) session.getAttribute("user");

        Report report = reportDao.findByIdAndUser(reportId, user);

        response.setHeader("Content-Disposition", "attachment;filename=".concat(report.getName()));

        return report.getFile();
    }

}

src/main/webapp/jsp/configuration.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>

    <tags:header />

    <body>

        <tags:navbar />

        <div class="container-fluid">
            <div class="row">

                <tags:sidebar currentPage="configurations" />

                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <h1 class="page-header">${configuration.name}</h1>

                    <br />

                    <c:choose>
                        <c:when test="${not empty currentSimulation}">
                            <h2 class="sub-header">Executing simulation ...</h2>
                            <div>
                                <div id="progressExecution" class="progress active">
                                    <div id="progress" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div>
                                </div>
                            </div>
                        </c:when>
                        <c:otherwise>
                            <h2 class="sub-header">Run simulation</h2>
                            <p>
                            <form method="POST" action="${pageContext.request.contextPath}/sim/execute/${configuration.id}">
                                <table>
                                    <tr>
                                        <td><input type="submit" value="Run" name="execute" id="execute" /></td>
                                    </tr>
                                </table>
                            </form>
                            </p>
                        </c:otherwise>
                    </c:choose>

                    <c:if test="${not empty simulations}">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Start time</th>
                                    <th>End Time</th>
                                    <th>Status</th>
                                    <th>Report</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <c:forEach items="${simulations}" var="simulation" >
                                        <tr>
                                            <td>${simulation.id}</td>
                                            <td>${simulation.start}</td>
                                            <td>${simulation.end}</td>
                                            <td>${simulation.state}</td>
                                            <td><a href=${pageContext.request.contextPath}/sim/configuration/report/${simulation.report.id}>${simulation.report.name}</a></td>
                                        </tr>
                                   </c:forEach>
                                </tbody>
                            </table>
                        </div>
                    </c:if>

                    <h2 class="sub-header">Reports</h2>

                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Execution time</th>
                                    <th>Size <small>(KB)</small></th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:choose>
                                    <c:when test="${not empty reports}">
                                        <c:forEach items="${reports}" var="report" >
                                            <tr>
                                                <td><a href=${pageContext.request.contextPath}/sim/configuration/report/${report.id}>${report.name}</a></td>
                                                <td>${report.executionTime}</td>
                                                <td>${report.size}</td>
                                                <td>${report.state}</td>
                                            </tr>
                                        </c:forEach>
                                    </c:when>
                                    <c:otherwise>
                                        <tr><td>No reports!</td></tr>
                                    </c:otherwise>
                                </c:choose>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <tags:bottom />

        <c:if test="${not empty currentSimulation}">
            <script language="javascript">

                $(document).ready(function(){
                    var progressExecution = setInterval(function(){
                        $.get("${pageContext.request.contextPath}/sim/executing/${configuration.id}", function(data){
                            $("#progress").css('width', data.progress + '%');
                            $("#progress").html(data.progress + '%');

                            if(data.progress > 99.999 || data.executing == false) {
                                clearInterval(progressExecution);
                                $("#progressExecution").removeClass("active");
                                $("#progress").html("Done");
                                location.reload(true);
                            }
                        })
                    }, 1000);
                });
            </script>
        </c:if>
    </body>
</html>

src/main/webapp/jsp/configurations.jsp
<!--
* Base Bootstrap Layout Template downloaded from url
* http://getbootstrap.com/examples/dashboard/
* No Copyright found
-->

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>

	<tags:header />

	<body>

		<tags:navbar />

		<div class="container-fluid">
			<div class="row">

				<tags:sidebar currentPage="configurations" />

				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					<h1 class="page-header">Simulation</h1>

					<div class="upload-configuration">
						<form method="POST" id="upload-form" action="${pageContext.request.contextPath}/sim/configurations/upload" enctype="multipart/form-data">
							<h2 class="sub-header">Upload configuration file</h2>

							<div class="row">
								<div class="col-sm-2">
									<input type="file" name="configurationFile" id="configurationFile" />
								</div>
							</div>
							<div class="row">
								<div class="progress" style="display: none">
									<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div>
								</div>
							</div>
							<p />
							<div class="row">
								<div class="col-sm-2">
									<button type="submit" name="upload" id="upload" class="btn btn-lg btn-primary btn-block">Upload</button>
								</div>
							</div>
						</form>
					</div>

					<div class="table-responsive">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>Name</th>
									<th>Uploaded time</th>
									<th>Size <small>(KB)</small></th>
								</tr>
							</thead>
							<tbody>
								<c:forEach items="${configurations}" var="configuration" >
								<tr>
									<td><a href=${pageContext.request.contextPath}/sim/configuration/${configuration.id}>${configuration.name}</a></td>
									<td>${configuration.uploadedTime}</td>
									<td>${configuration.size}</td>
								</tr>
								</c:forEach>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

		<tags:bottom />

		<script src="${pageContext.request.contextPath}/js/jquery.form.min.js" rel="stylesheet" ></script>
		<script src="${pageContext.request.contextPath}/js/upload.js" rel="stylesheet" ></script>
	</body>
</html>

src/main/webapp/jsp/main.jsp
<!--
* Base Bootstrap Css Layout Template downloaded from url
* http://getbootstrap.com/examples/dashboard/
* No Copyright found
-->

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>

<tags:header />

	<body>

		<tags:navbar />

		<div class="container-fluid">
			<div class="row">
				<tags:sidebar />

				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					<h1 class="page-header">Dashboard</h1>

					<div class="row placeholders">
						<div class="col-xs-6 col-sm-3 placeholder">
							<img src="${pageContext.request.contextPath}/images/ScreenShotCafeModel.png" width="200" height="200" class="img-responsive" alt="Cafe Model">
							<h4>Cafe Model</h4>
							<span class="text-muted">Get more info</span>
						</div>
						<div class="col-xs-6 col-sm-3 placeholder">
							<img src="${pageContext.request.contextPath}/images/ScreenShotHarmonicOscillator.png" width="200" height="200" class="img-responsive" alt="Harmonic Oscillator">
							<h4>Harmonic Oscillator</h4>
							<span class="text-muted">Get statistics</span>
						</div>
						<div class="col-xs-6 col-sm-3 placeholder">
							<img src="${pageContext.request.contextPath}/images/ScreenShotFerrariDaytona.png" width="200" height="200" class="img-responsive" alt="Ferrari Daytona">
							<h4>Ferrari Daytona</h4>
							<span class="text-muted">Get more info</span>
						</div>
						<div class="col-xs-6 col-sm-3 placeholder">
							<img src="${pageContext.request.contextPath}/images/ScreenShotServerAndQueue.png" width="200" height="200" class="img-responsive" alt="Server And Queue">
							<h4>Server And Queue</h4>
							<span class="text-muted">Get more results</span>
						</div>
					</div>

					<h2 class="sub-header">Simulations</h2>
					<c:choose>
						<c:when test="${not empty simulations}">
							<div class="table-responsive">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Name</th>
											<th>Simulation Start Time</th>
											<th>Simulation End Time</th>
											<th>Status</th>
										</tr>
									</thead>
									<tbody>
										<c:forEach items="${simulations}" var="simulation">
											<tr>
												<td><a href="${pageContext.request.contextPath}/sim/configuration/${simulation.configuration.id}">${simulation.configuration.name}</a></td>
												<td>${simulation.start}</td>
												<td>${simulation.end}</td>
												<td>${simulation.state}</td>
											</tr>
										</c:forEach>
									</tbody>
								</table>
							</div>
						</c:when>
						<c:otherwise>No simulations! Please go to configurations and run one!</c:otherwise>
					</c:choose>
				</div>
			</div>
		</div>

		<tags:bottom />
	</body>
</html>